# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trellodemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_text',
            new_name='boardname',
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='board',
            name='last_modified',
        ),
    ]
