# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 09:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trellodemo', '0002_auto_20160721_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_by',
            field=models.CharField(default=datetime.datetime(2016, 7, 21, 9, 21, 45, 111869, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
