# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trellodemo', '0006_auto_20160722_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_time',
        ),
    ]
