# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trellodemo', '0007_remove_card_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='description',
        ),
    ]
